### ISSUE TITLE
[Feature Request] - Windows support

### ISSUE THREAD

**Issue by orazdow** [margual56/radio-cli#25]
thought I'd ask before trying, I'm on w11

**Comment by margual56** [comment]
Hello! 

It does not compile on Windows due to a dependency on the [xdg](https://crates.io/crates/xdg) library for getting the configuration directory. It only works on Linux systems (as far as I know).

Besides that, there's no reason why it shouldn't work on Windows.

If anyone is interested in having a look at it and adding Windows support (changing the library xdg for a different one, or adding a `#[cfg]` statement) feel free to create a pull request 😄.

**Comment by orazdow** [comment]
Ah ok, yeah it seems specific to X windows. I'll just install it on my next mint partition.

**Comment by margual56** [comment]
@orazdow 

![image](https://github.com/margual56/radio-cli/assets/30444886/a3572e6e-022a-463b-8fda-c92c1bc9e88e)

I have added support for Windows! I checked and it works :)
It should also work on Mac.

I will release the new version tomorrow or the day after. If you want to use it now, you can use the `dev` branch. Enjoy!

_Note: Remember to have `mpv` installed and in the PATH, and `yt-dlp` if you want to be able to listen to youtube things_

**Comment by orazdow** [comment]
Woo that's awesome.

I built it with rust on msys2 and it works. Although it seems there are 2 bugs: It doesn't seem to stop playing through mpv for me when I press q or quit the program. Also the lofi station ended the process so maybe it's not handling invalid urls? Everything else works though.

**Comment by margual56** [comment]
True... I think this is more of a _Rust_ issue, because on Linux it works flawlessly. I'll have to have a look at it.

**Comment by orazdow** [comment]
Yeah or maybe the way Linux commands and processes work vs Windows is too different. Or even MPV. 
Maybe it's not worth too much trouble. I noticed ffplay works really well to play streams on Windows so I might try using a script to emulate the config.json feature of radio-cli with that 😁.
